---
- hosts: loadbalancer
  become: true
  tasks:
    - name: install nginix
      apt: name=nginix state=present update_cache=yes

    - name: ensure nginix started
      service: name=nginix state=started enabled=yes
